# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\x1csample_service.sample_module\x1a\x1cgoogle/api/annotations.proto\"6\n\x0eOperandMessage\x12\x11\n\toperand_1\x18\x01 \x01(\x05\x12\x11\n\toperand_2\x18\x02 \x01(\x05\" \n\x0eResultResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\xb3\x02\n\rSampleService\x12\x8e\x01\n\nAddRequest\x12,.sample_service.sample_module.OperandMessage\x1a,.sample_service.sample_module.ResultResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/add/{operand_1}/{operand_2}\x12\x90\x01\n\nSubRequest\x12,.sample_service.sample_module.OperandMessage\x1a,.sample_service.sample_module.ResultResponse\"&\x82\xd3\xe4\x93\x02 \"\t/subtract:\x01*Z\x10\"\x0b/SubRequest:\x01*B\x18Z\x16sample_service/gatewayb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\026sample_service/gateway'
  _SAMPLESERVICE.methods_by_name['AddRequest']._options = None
  _SAMPLESERVICE.methods_by_name['AddRequest']._serialized_options = b'\202\323\344\223\002\036\022\034/add/{operand_1}/{operand_2}'
  _SAMPLESERVICE.methods_by_name['SubRequest']._options = None
  _SAMPLESERVICE.methods_by_name['SubRequest']._serialized_options = b'\202\323\344\223\002 \"\t/subtract:\001*Z\020\"\013/SubRequest:\001*'
  _OPERANDMESSAGE._serialized_start=76
  _OPERANDMESSAGE._serialized_end=130
  _RESULTRESPONSE._serialized_start=132
  _RESULTRESPONSE._serialized_end=164
  _SAMPLESERVICE._serialized_start=167
  _SAMPLESERVICE._serialized_end=474
# @@protoc_insertion_point(module_scope)
