# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sample_pb2 as sample__pb2


class SampleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddRequest = channel.unary_unary(
                '/sample_service.sample_module.SampleService/AddRequest',
                request_serializer=sample__pb2.OperandMessage.SerializeToString,
                response_deserializer=sample__pb2.ResultResponse.FromString,
                )
        self.SubRequest = channel.unary_unary(
                '/sample_service.sample_module.SampleService/SubRequest',
                request_serializer=sample__pb2.OperandMessage.SerializeToString,
                response_deserializer=sample__pb2.ResultResponse.FromString,
                )


class SampleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SampleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRequest,
                    request_deserializer=sample__pb2.OperandMessage.FromString,
                    response_serializer=sample__pb2.ResultResponse.SerializeToString,
            ),
            'SubRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.SubRequest,
                    request_deserializer=sample__pb2.OperandMessage.FromString,
                    response_serializer=sample__pb2.ResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sample_service.sample_module.SampleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SampleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sample_service.sample_module.SampleService/AddRequest',
            sample__pb2.OperandMessage.SerializeToString,
            sample__pb2.ResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sample_service.sample_module.SampleService/SubRequest',
            sample__pb2.OperandMessage.SerializeToString,
            sample__pb2.ResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
